### ISSUE TITLE
couldn't connect to aerospike docker container.

### ISSUE THREAD

**Issue by komalbb** [ory/dockertest#213]
I tried multiple things, but the connection is timing out; 
err: 2020/09/14 01:13:14 Could not connect to aerospike docker:Failed to connect to hosts:dial tcp 127.0.0.1:3000: connect: connection refused
dial tcp [::1]:3000: connect: connection refused
Can you please help here, how to get aerospike connection be successful. 
resource, err := pool.RunWithOptions(&dockertest.RunOptions{
		Repository: "aerospike/aerospike-server",
		//Tag:          "5.1.0.6",
		//ExposedPorts: []string{"3000", "3001", "3002"},
		Env: []string{},
	})
	if err != nil {
		log.Printf("Could not start resource: %s", err)
		return err
	}
	fix.Aerospike.resource = resource
	if err := pool.Retry(func() error {
		var err error
		ac, err = as.NewClientWithPolicyAndHost(nil, &as.Host{Name: "localhost", Port: 3000})
		if err != nil {
			return err
		}
		return nil
	}); err != nil {
		log.Printf("Could not connect to aerospike docker:%s", err)
		return err
	}

 docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by komalbb** [comment]
Fixed it; by getting address from the resource and using it to connect to aerospike  addr := resource.Container.NetworkSettings.IPAddress
