### ISSUE TITLE
Add documentation to increase accessibility for docker users to pick up and go faster

### ISSUE THREAD

**Issue by benjamin-rood** [ory/dockertest#279]
**Is your feature request related to a problem? Please describe.**

There is a lack of blatant documentation in this library, and that effects the speed with which someone can hit the ground running.The examples provided are _all_ trivial, and they provide no proper container execution options at all.

An obvious case: For ease of use, please can we add a docstring to every `RunOption` field which lists the *equivalent* flag(s) that correspond 1:1 with docker-cli operation. Everyone who would come looking to use this library wants to be able to map their execution experience with either the cli or Dockerfile operation to this library.

How these things are named is how they are named (I personally would have every field named to exactly match `docker` flags e.g. the option to match `--publish` could have just been `Publish` instead of `ExposedPorts`, and I would have used the identical syntax to the flag and just parsed that for the user, rather than splitting the functionality across `ExposedPorts` and `PortBindings`... but, I do understand the rationale. However, when doing this, that naming necessitates some documentation to make it explicit how to take an example and execute it in the library.
Of course, some things are pretty obvious, like `<image>:<tag>` maps to `Repository` and `Tag`, `--env` / `-e` to `Env`, and `--name` / `-n` to `Name` fields respectively, but there's _no harm in spelling that out_ even in these cases.

For example, my understanding would be that `neo4j:latest --env=NEO4J_AUTH=none --publish=7474:7474 --publish=7687:7687` (common execution port bindings needed for running Neo4j inside a docker container) maps to: 

    	opts := dockertest.RunOptions{
		Repository:   "neo4j",
		Tag:          "latest",
		Env:          []string{"NEO4J_AUTH=none"},
		ExposedPorts: []string{"7474", "7687"},
		PortBindings: map[docker.Port][]docker.PortBinding{
			"7474": {
				{HostIP: "0.0.0.0", HostPort: "7474"},
			},
			"7687": {
				{HostIP: "0.0.0.0", HostPort: "7687"},
			},
		},
	}

The fact that those bindings aren't really needed when standing up a container that will be stood up and torn down again as fast as possible is really irrelevant. It's the first thing I would be looking for to quickly map my expectation from a docker cli command or Dockerfile configuration I am used to running onto how to use this library.

**Describe the solution you'd like**

As per description above, the best initial use of time would be to document such that 
I am happy to do a PR for this myself... except I don't fully know how the library works! If we could have some discussion to clarify, I can then do the work to add the documentation inline to the code, making sure the next person doesn't have to scratch their head.

I envision this being an iterative process, filling out the documentation in blocks at a time and PRs for each.

This isn't a question of being entitled, I'm happy to put my shoulder to the wheel. It's about recognising that as developers we are constantly having to look up how to use this API, that library, etc, and it's very frustrating when we have to spend time trying to understand the design decisions of a library or API rather spending that time writing and pushing code that uses said library or API in order to solve the problem you are under pressure to address. We don't have the usage context that the library author(s) have which might make it "obvious", so let's address that with documentation.

**Comment by aeneasr** [comment]
Hello, thank you for the extensive feedback. Dockertest is a library to quickly get some system dependencies off the ground (e.g. mysql). It's not a replacement for docker swarm, docker compose, kubernetes, or other complex orchestration systems. It was never designed to be that! The examples are trivial because the use case for dockertest is somewhat trivial. Start a off-the-mill docker container from Go and delete it once your test completed.

However, contributors keep adding things like envs, custom exec commands, and so on as they try to cover edge cases. Usually, these contributions do not include documentation.

My recommendation is to not use dockertest if you require 6 containers in orchestration doing things which custom mount points and whatnot. Instead, run `docker-compose up` before your test (you can even do it using os.exec in Go) with whatever you need.

Still, adding docs to this library would be nice and we highly welcome contributions in that direction. I myself will unfortunately not be able to assist (except during review) due to time constraints and other priorities. I hope you understand!
